// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2YgNgkkbnQVRDMOUnatp__Pds5nkZBLU',
    appId: '1:678735893396:web:56ba2efd9ba9572a443581',
    messagingSenderId: '678735893396',
    projectId: 'tiktok-4e762',
    authDomain: 'tiktok-4e762.firebaseapp.com',
    storageBucket: 'tiktok-4e762.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3pxmdTf55LtZb-k8nbUAqx8HfXD-A0c',
    appId: '1:678735893396:android:432bbea2e57fbbe0443581',
    messagingSenderId: '678735893396',
    projectId: 'tiktok-4e762',
    storageBucket: 'tiktok-4e762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCcTH-GzLOV2H51AhGFJUCXelO62luT0',
    appId: '1:678735893396:ios:da88ee83473591d4443581',
    messagingSenderId: '678735893396',
    projectId: 'tiktok-4e762',
    storageBucket: 'tiktok-4e762.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCcTH-GzLOV2H51AhGFJUCXelO62luT0',
    appId: '1:678735893396:ios:da88ee83473591d4443581',
    messagingSenderId: '678735893396',
    projectId: 'tiktok-4e762',
    storageBucket: 'tiktok-4e762.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );
}